version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    labels:
      - "meta: CI"
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /
    target-branch: master
    labels:
      - "meta: deps"
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"
