ci:
  autoupdate_branch: "master"
  autoupdate_commit_msg: "⬆️ update pre-commit hooks"

exclude: "^mt940_tests/self-provided/"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml

      - id: check-vcs-permalinks
      - id: check-xml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]
        types_or: [python, pyi]

      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ['--skip="*/htmlcov,./docs/_build,*.asc,*.yml,*.sta,*.txt,*.html,./docs/html"']

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.4.2"
    hooks:
      - id: prettier
        types_or: ['markdown']
