env_list = [
    'fix',
    'clean',
    'py39',
    'py310',
    'py311',
    'py312',
    # pypy3 works just fine but the tests fail due to pypy import weirdness
    # 'pypy3',
    'docs',
    'mypy',
    'pyright',
    'ruff',
    'repo-review',
    'codespell',
]
skip_missing_interpreters = true

[env_run_base]
pass_env = ['FORCE_COLOR']
commands = [['pytest', '--cov-append', '{posargs}']]
extras = ['tests', 'docs']

[env.fix]
description = 'run code formatter and linter (auto-fix)'
skip_install = true
deps = 'pre-commit-uv'
commands = [['pre-commit', 'run', '--all-files', '--show-diff-on-failure']]

[env.clean]
deps = ['coverage']
skip_install = true
commands = [['coverage', 'erase']]

[env.mypy]
commands = [['mypy']]

[env.pyright]
commands = [['pyright']]

[env.ruff]
deps = ['ruff']
commands = [['ruff', 'check'], ['ruff', 'format', '--check']]

[env.docs]
extras = ['docs']
allowlist_externals = ['rm', 'cd', 'mkdir']
commands = [
    [
        'rm',
        '-vf',
        'docs/mt940.json.rst',
    ],
    [
        'rm',
        '-vf',
        'docs/mt940.models.rst',
    ],
    [
        'rm',
        '-vf',
        'docs/mt940.parser.rst',
    ],
    [
        'rm',
        '-vf',
        'docs/mt940.processors.rst',
    ],
    [
        'rm',
        '-vf',
        'docs/mt940.rst',
    ],
    [
        'rm',
        '-vf',
        'docs/mt940.tags.rst',
    ],
    [
        'rm',
        '-vf',
        'docs/mt940.utils.rst',
    ],
    [
        'mkdir',
        '-p',
        'docs/_static',
    ],
    [
        'sphinx-apidoc',
        '--separate',
        '--module-first',
        '--output-dir',
        'docs/',
        'mt940',
    ],
    [
        'sphinx-build',
        '-W',
        '-b',
        'html',
        '-d',
        'docs/doctrees',
        'docs',
        'docs/html',
    ],
]

[env.repo-review]
basepython = ['py312']
deps = ['sp-repo-review[cli]', 'validate-pyproject']
commands = [['repo-review', '--show=err']]

[env.codespell]
commands = [['codespell']]
deps = ['codespell', 'tomli']
skip_install = true
command = 'codespell'
